description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
  http: ^0.13.4
  provider: ^6.0.3
  flutter_provider: ^2.1.0
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "DM Sans"
      fonts: 
        - 
          asset: "fonts/DMSans-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/DMSans-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-100.ttf"
          style: "normal"
          weight: 100
  uses-material-design: true
