import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_refreshWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_backButtonWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_box3Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedBaseWidget10.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_box2Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedWidget40.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedCardCardSeparatorWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_box4Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_box5Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_box1Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_tag2Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedRectangle124Widget9.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_tag3Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_tag1Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_tag5Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemswidget/generated/GeneratedProblems_tag4Widget.dart';

import '../generatedproblemwidget/GeneratedProblemWidget.dart';
import 'package:http/http.dart' as http;

/* Frame problems
    Autogenerated by FlutLab FTF Generator
  */

class GeneratedProblemsWidget extends StatelessWidget {
  const GeneratedProblemsWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ProblemsPage();
  }
}


class ProblemsPage extends StatefulWidget {
  const ProblemsPage({Key key}) : super(key: key);

  @override
  State<ProblemsPage> createState() => _ProblemsPageState();
}

class _ProblemsPageState extends State<ProblemsPage> {
  final _biggerFont = const TextStyle(fontSize: 13); // 스타일
  var _idList;
  var _strList;

  @override
  void initState() {
    // 서버 통신.
    // TODO: implement initState
    super.initState();
    _asyncMethod();
  }

  _asyncMethod() async {
    final response_ID = await http.get(
        Uri.parse('http://127.0.0.1:5000/problems/id'));
    final decoded_ID = json.decode(response_ID.body) as List<dynamic>;

    final response_str = await http.get(
        Uri.parse('http://127.0.0.1:5000/problems/str'));
    final decoded_str = json.decode(response_str.body) as List<dynamic>;
    setState(() {
      _idList = decoded_ID;
      _strList = decoded_str;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.circular(30.0),
          child: Container(
            width: 375.0,
            height: 812.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(30.0),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(30.0),
                    child: Container(
                      color: Color.fromARGB(255, 99, 95, 255),
                    ),
                  ),
                  Positioned(
                    left: 376.0,
                    top: 202.0,
                    right: null,
                    bottom: null,
                    width: 375.99993896484375,
                    height: 610.0000610351562,
                    child: GeneratedRectangle124Widget9(),
                  ),
                  Positioned(
                    left: 29.0,
                    top: 148.0,
                    right: null,
                    bottom: null,
                    width: 140.0,
                    height: 35.0,
                    child: GeneratedGroup4Widget(),
                  ),
                  Positioned(
                    left: 30.0,
                    top: 122.0,
                    right: null,
                    bottom: null,
                    width: 314.0,
                    height: 0.0,
                    child: GeneratedCardCardSeparatorWidget2(),
                  ),
                  Positioned(
                    left: 28.0,
                    top: 228.0,
                    right: null,
                    bottom: null,
                    width: 57.0,
                    height: 20.0,
                    child: InkWell(
                      onTap: (){
                        setState(() {
                          _asyncMethod();
                        });
                      },
                      child: Text(
                        '''새로 고침''',
                        overflow: TextOverflow.visible,
                        textAlign: TextAlign.left,

                        style: TextStyle(
                          height: 1.171875,
                          fontSize: 14.0,
                          fontFamily: 'DM Sans',
                          fontWeight: FontWeight.w700,
                          color: Color.fromARGB(255, 22, 23, 25),

                          /* letterSpacing: 0.0, */
                        ),

                      ),
                    )

                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: null,
                    bottom: null,
                    width: 375.0,
                    height: 44.0,
                    child: GeneratedBaseWidget10(),
                  ),
                  Positioned(
                    left: 38.0,
                    top: 94.0,
                    right: null,
                    bottom: null,
                    width: 112.0,
                    height: 20.0,
                    child: GeneratedWidget40(),
                  ),
                  // Positioned(
                  //   left: 24.0,
                  //   top: 376.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 325.0,
                  //   height: 105.0,
                  //   child: GeneratedProblems_box2Widget(),
                  // ),
                  // Positioned(
                  //   left: 25.0,
                  //   top: 261.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 325.0,
                  //   height: 105.0,
                  //   child: GeneratedProblems_box1Widget(),
                  // ),
                  Positioned(
                    left: 24.0,
                    top: 250.0,
                    right: null,
                    bottom: null,
                    width: 325.0,
                    height: 500.0,
                    child: ListView.builder(
                        itemCount: _idList.length,
                        itemBuilder: (BuildContext context, int index) {
                          return ListTile(
                            onTap: () async {
                              final item_id = _idList[index];
                              final result = await Navigator.push(
                                context,
                                CupertinoPageRoute(builder: (context)=>GeneratedProblemWidget(problem_id:item_id)),
                              );
                            },
                            title: Container(
                              alignment: Alignment.centerLeft,
                              height: 70,
                              child: Text(_strList[index], textAlign: TextAlign.start,style: _biggerFont,),
                            ),
                          );
                        })
                  ),
                  // Positioned(
                  //   left: 24.0,
                  //   top: 714.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 325.0,
                  //   height: 105.0,
                  //   child: GeneratedProblems_box5Widget(),
                  // ),
                  // Positioned(
                  //   left: 24.0,
                  //   top: 488.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 325.0,
                  //   height: 105.0,
                  //   child: GeneratedProblems_box3Widget(),
                  // ),
                  // Positioned(
                  //   left: 274.0,
                  //   top: 326.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 68.0,
                  //   height: 17.0,
                  //   child: GeneratedProblems_tag1Widget(),
                  // ),
                  // Positioned(
                  //   left: 274.0,
                  //   top: 440.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 68.0,
                  //   height: 17.0,
                  //   child: GeneratedProblems_tag2Widget(),
                  // ),
                  // Positioned(
                  //   left: 268.0,
                  //   top: 544.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 68.0,
                  //   height: 17.0,
                  //   child: GeneratedProblems_tag3Widget(),
                  // ),
                  // Positioned(
                  //   left: 268.0,
                  //   top: 654.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 68.0,
                  //   height: 17.0,
                  //   child: GeneratedProblems_tag4Widget(),
                  // ),
                  // Positioned(
                  //   left: 268.0,
                  //   top: 772.0,
                  //   right: null,
                  //   bottom: null,
                  //   width: 68.0,
                  //   height: 17.0,
                  //   child: GeneratedProblems_tag5Widget(),
                  // ),
                  Positioned(
                    left: 326.0,
                    top: 59.0,
                    right: null,
                    bottom: null,
                    width: 20.0,
                    height: 20.0,
                    child: GeneratedProblems_backButtonWidget(),
                  )
                ]),
          ),
        ));
  }
}

