import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedGroup6Widget2.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedChicksolutionWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedGroup7Widget11.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro141widget/generated/GeneratedRectangle2Widget1.dart';

/* Frame MacBook Pro 14" - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro141Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 982.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 12.0,
                              right: null,
                              bottom: null,
                              width: 488.0,
                              height: 93.0,
                              child: GeneratedChicksolutionWidget(),
                            ),
                            Positioned(
                              left: 421.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 1091.0,
                              height: 764.0,
                              child: GeneratedImage1Widget1(),
                            ),
                            Positioned(
                              left: 1368.0,
                              top: 25.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 96.0,
                              child: GeneratedGroup1Widget(),
                            ),
                            Positioned(
                              left: 562.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 722.0,
                              height: 59.0,
                              child: GeneratedRectangle2Widget1(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 120.0,
                              child: GeneratedGroup4Widget1(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 120.0,
                              child: GeneratedGroup5Widget(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 120.0,
                              child: GeneratedGroup6Widget2(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 664.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 120.0,
                              child: GeneratedGroup7Widget11(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 825.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 120.0,
                              child: GeneratedGroup8Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
