import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedCardPreBuildWidget14.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedVectorWidget62.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedWidget28.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedCardPreBuildWidget13.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedRectangle124Widget7.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedCardPreBuildWidget9.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedBaseMenuNavigationWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedVectorWidget60.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedCardPreBuildWidget11.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedCardPreBuildWidget10.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedBaseFormInputWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedVectorWidget59.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedCardPreBuildWidget12.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedVectorWidget61.dart';
import 'package:flutterapp/easyandquickapp/generatedsearch_completewidget/generated/GeneratedBaseWidget7.dart';

/* Frame search_complete
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearch_completeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 99, 95, 255),
                ),
              ),
              Positioned(
                left: 376.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 375.99993896484375,
                height: 711.0000610351562,
                child: GeneratedRectangle124Widget7(),
              ),
              Positioned(
                left: 25.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 20.0,
                child: GeneratedWidget28(),
              ),
              Positioned(
                left: 4.547473508864641e-13,
                top: 53.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 40.0,
                child: GeneratedBaseMenuNavigationWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 50.0,
                child: GeneratedBaseFormInputWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 503.0,
                child: GeneratedCardPreBuildWidget9(),
              ),
              Positioned(
                left: 24.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 87.0,
                child: GeneratedCardPreBuildWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 105.0,
                child: GeneratedCardPreBuildWidget11(),
              ),
              Positioned(
                left: 25.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 105.0,
                child: GeneratedCardPreBuildWidget12(),
              ),
              Positioned(
                left: 25.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 105.0,
                child: GeneratedCardPreBuildWidget13(),
              ),
              Positioned(
                left: 25.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 105.0,
                child: GeneratedCardPreBuildWidget14(),
              ),
              Positioned(
                left: 320.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget59(),
              ),
              Positioned(
                left: 321.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget60(),
              ),
              Positioned(
                left: 323.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget61(),
              ),
              Positioned(
                left: 323.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget62(),
              ),
              Positioned(
                left: 1.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget7(),
              ),
              Positioned(
                left: -1.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedGroup9Widget(),
              )
            ]),
      ),
    ));
  }
}
