import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedQnAWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedRectangle124Widget5.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedCommentWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedSmallBadgeWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedGroup31Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedGroup13Widget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedGroup21Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedBaseWidget5.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedGroup32Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedRectangle136Widget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedSearchWidget5.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedImage6Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_threewidget/generated/GeneratedGroup30Widget3.dart';

/* Frame qna_three
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQna_threeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 252, 252, 255),
                ),
              ),
              Positioned(
                left: 330.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedSearchWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.000030517578125,
                right: null,
                bottom: null,
                width: 376.0,
                height: 74.00003051757812,
                child: GeneratedRectangle124Widget5(),
              ),
              Positioned(
                left: 302.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 18.0,
                child: GeneratedGroup21Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 70.00003051757812,
                child: GeneratedRectangle136Widget2(),
              ),
              Positioned(
                left: 15.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 198.0,
                child: GeneratedCommentWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget5(),
              ),
              Positioned(
                left: 15.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 19.79069709777832,
                child: GeneratedGroup13Widget2(),
              ),
              Positioned(
                left: 17.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 31.0,
                child: GeneratedQnAWidget2(),
              ),
              Positioned(
                left: 337.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget34(),
              ),
              Positioned(
                left: 96.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 24.0,
                child: GeneratedGroup30Widget3(),
              ),
              Positioned(
                left: 12.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 348.34210205078125,
                height: 186.0,
                child: GeneratedImage6Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 267.999755859375,
                height: 15.0,
                child: GeneratedGroup31Widget1(),
              ),
              Positioned(
                left: 285.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 14.0,
                child: GeneratedSmallBadgeWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 81.0,
                child: GeneratedGroup32Widget(),
              )
            ]),
      ),
    ));
  }
}
