import 'dart:convert';
import 'dart:math';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedBaseWidget9.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedRectangle127Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedCardCardSeparatorWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedRectangle128Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedProblem_button_groupWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedproblemwidget/generated/GeneratedProblem_RectangleWidget.dart';

import 'generated/GeneratedCheckoutNowWidget.dart';
import 'generated/GeneratedCheckoutNowWidget1.dart';
import 'generated/GeneratedGroup32Widget1.dart';
import 'package:http/http.dart' as http;
import 'dart:math';

/* Frame problem
    Autogenerated by FlutLab FTF Generator
  */

class GeneratedProblemWidget extends StatelessWidget {
  final problem_id;
  GeneratedProblemWidget({Key key, this.problem_id}) : super(key: key);



  @override
  Widget build(BuildContext context) {
    return Problem_page(problem_id: problem_id);
  }
}

class Problem_page extends StatefulWidget {
  final problem_id;
  const Problem_page({Key key, this.problem_id}) : super(key: key);

  @override
  State<Problem_page> createState() => _Problem_pageState();
}

class _Problem_pageState extends State<Problem_page> {
  // var _name;
  var _str;
  var _tag;
  var _idList;
  var next_id;
  var _imageUrl;
  var _strList;


  @override
  void initState() {
    // 서버 통신.
    // TODO: implement initState
    super.initState();

    _imageUrl = "solution/null.png";
    _asyncMethod();
    _post();
    _get();




  }

  _get() async {
    final response = await http.get(
        Uri.parse('http://127.0.0.1:5000/problem/get'));
    final decoded = json.decode(response.body) as Map<String, dynamic>;
    setState(() {
      // _name = decoded['name'];
      // _bookmark = decoded['bookmark'];
      // _like = decoded['like'];
      _str = decoded['str'];
      _tag = decoded['tag'];
    });
  }

  _post() async {
    String url = 'http://127.0.0.1:5000/problem/get';
    final response = await http.post(
        Uri.parse(url), body: json.encode({'id': widget.problem_id}));
  }

  _asyncMethod() async {
    final response_ID = await http.get(
        Uri.parse('http://127.0.0.1:5000/problems/id'));
    final decoded_ID = json.decode(response_ID.body) as List<dynamic>;

    final response_str = await http.get(
        Uri.parse('http://127.0.0.1:5000/problems/str'));
    final decoded_str = json.decode(response_str.body) as List<dynamic>;
    setState(() {
      _idList = decoded_ID;
      _strList = decoded_str;

      next_id = _idList[Random().nextInt(4)];
    });
  }

  @override
  Widget build(BuildContext context) {
      return Material(
          child: ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              width: 375.0,
              height: 812.0,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(30.0),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(30.0),
                      child: Container(
                        color: Color.fromARGB(255, 99, 95, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 207.0,
                      right: null,
                      bottom: null,
                      width: 375.99993896484375,
                      height: 605.0000610351562,
                      child: GeneratedProblem_RectangleWidget(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 406.0,
                      right: null,
                      bottom: null,
                      width: 46.0,
                      height: 21.0,
                      child: InkWell(
                        onTap: (){
                          setState(() {
                            _asyncMethod();
                          });
                        },
                        child: Text(
                          '''Answer''',
                          overflow: TextOverflow.visible,
                          textAlign: TextAlign.left,
                          style: TextStyle(
                            height: 1.171875,
                            fontSize: 12.0,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w400,
                            color: Color.fromARGB(255, 99, 95, 255),

                            /* letterSpacing: 0.0, */
                          ),
                        ),
                      )
                    ),
                    Positioned(
                      left: 25.0,
                      top: 454.0,
                      right: null,
                      bottom: null,
                      width: 50.0,
                      height: 21.0,
                      child: InkWell(
                        onTap: (){
                          setState(() {
                            _imageUrl = "solution/" + widget.problem_id + ".png";
                          });
                        },
                        child: Text(
                          '''Solution''',
                          overflow: TextOverflow.visible,
                          textAlign: TextAlign.left,
                          style: TextStyle(
                            height: 1.171875,
                            fontSize: 12.0,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w400,
                            color: Color.fromARGB(255, 99, 95, 255),

                            /* letterSpacing: 0.0, */
                          ),
                        ),
                      ), // 솔루션 위젯
                    ),
                    Positioned(
                        left: 25.0,
                        top: 504.0,
                        right: null,
                        bottom: null,
                        width: 300.0,
                        height: 150.0,
                        child: Image.asset(_imageUrl),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 441.0,
                      right: null,
                      bottom: null,
                      width: 325.0,
                      height: 0.0,
                      child: GeneratedCardCardSeparatorWidget1(),
                    ),
                    Positioned(
                        left: 0.0,
                        top: 82.0,
                        right: null,
                        bottom: null,
                        width: 376.0,
                        height: 324.0,
                        child: ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Container(
                            width: 376.0,
                            height: 324.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: 16.0,
                                    top: 13.0,
                                    right: null,
                                    bottom: null,
                                    width: 290.0,
                                    height: 33.0,
                                    child: Text(
                                      "문제 " + widget.problem_id + "번",
                                      overflow: TextOverflow.visible,
                                      textAlign: TextAlign.left,
                                      style: TextStyle(
                                        height: 1.171875,
                                        fontSize: 24.0,
                                        fontFamily: 'DM Sans',
                                        fontWeight: FontWeight.w700,
                                        color: Color.fromARGB(255, 252, 252, 255),

                                        /* letterSpacing: 0.0, */
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 64.0,
                                    right: null,
                                    bottom: null,
                                    width: 82.0,
                                    height: 30.0,
                                    child: Container(
                                      width: 200.0,
                                      height: 30.0,
                                      decoration: BoxDecoration(
                                        borderRadius: BorderRadius.circular(100.0),
                                      ),
                                      child: Stack(
                                          fit: StackFit.expand,
                                          alignment: Alignment.center,
                                          overflow: Overflow.visible,
                                          children: [
                                            ClipRRect(
                                              borderRadius: BorderRadius.circular(100.0),
                                              child: Container(
                                                color: Color.fromARGB(255, 230, 229, 255),
                                              ),
                                            ),
                                            Positioned(
                                              left: 12.0,
                                              top: 8.5,
                                              right: null,
                                              bottom: null,
                                              width: 100.0,
                                              height: 15.0,
                                              child: Text(
                                                "$_tag",
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.171875,
                                                  fontSize: 10.0,
                                                  fontFamily: 'DM Sans',
                                                  fontWeight: FontWeight.w400,
                                                  color: Colors.red,

                                                  /* letterSpacing: 0.0, */
                                                ),
                                              ),
                                            )
                                          ]),
                                    ),
                                  ),
                                  Positioned(
                                      left: 10.0,
                                      top: 198.0,
                                      right: null,
                                      bottom: null,
                                      width: 350.0,
                                      height: 119.0,
                                      child: Text(
                                        "${_str}",
                                        overflow: TextOverflow.visible,
                                        textAlign: TextAlign.left,
                                        style: TextStyle(
                                          height: 1.171875,
                                          fontSize: 12.0,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          color: Color.fromARGB(
                                              255, 22, 23, 25),

                                          /* letterSpacing: 0.0, */
                                        ),
                                      )
                                  ),
                                  Positioned(
                                    left: 299.0,
                                    top: 166.0,
                                    right: null,
                                    bottom: null,
                                    width: 70.0,
                                    height: 15.0,
                                    child: GeneratedGroup32Widget1(),
                                  )
                                ]),
                          ),
                        )
                    ),
                    Positioned(
                      left: 110.0,
                      top: 44.0,
                      right: null,
                      bottom: null,
                      width: 47.11272430419922,
                      height: 47.11272430419922,
                      child: GeneratedRectangle128Widget(),
                    ),
                    Positioned(
                      left: 44.0,
                      top: 44.0,
                      right: null,
                      bottom: null,
                      width: 47.11272430419922,
                      height: 47.11272430419922,
                      child: GeneratedRectangle127Widget(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 736.0,
                      right: null,
                      bottom: null,
                      width: 325.0,
                      height: 48.0,
                      child: Container(
                        width: 325.0,
                        height: 48.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: null,
                                bottom: null,
                                width: 152.5,
                                height: 48.0,
                                child: GestureDetector(
                                  onTap: () async {
                                    final result = await Navigator.push(
                                        context,
                                        CupertinoPageRoute(builder: (context)=>GeneratedProblemWidget(problem_id:(Random().nextInt(25)+1).toString()))
                                    );

                                  },
                                  child: Container(
                                    width: 152.5,
                                    height: 48.0,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(10.0),
                                    ),
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        overflow: Overflow.visible,
                                        children: [
                                          ClipRRect(
                                            borderRadius: BorderRadius.circular(10.0),
                                            child: Container(
                                              color: Color.fromARGB(255, 99, 95, 255),
                                            ),
                                          ),
                                          Positioned(
                                            left: 63.25,
                                            top: 15.0,
                                            right: null,
                                            bottom: null,
                                            width: 31.0,
                                            height: 23.0,
                                            child: GeneratedCheckoutNowWidget(),
                                          )
                                        ]),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 172.5,
                                top: 0.0,
                                right: null,
                                bottom: null,
                                width: 152.5,
                                height: 48.0,
                                child: GestureDetector(
                                  onTap: () async {
                                    final result = await Navigator.push(
                                        context,
                                        CupertinoPageRoute(builder: (context)=>GeneratedProblemWidget(problem_id:next_id))
                                    );

                                  },
                                  child: Container(
                                    width: 152.5,
                                    height: 48.0,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(10.0),
                                    ),
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        overflow: Overflow.visible,
                                        children: [
                                          ClipRRect(
                                            borderRadius: BorderRadius.circular(10.0),
                                            child: Container(
                                              color: Color.fromARGB(255, 125, 197, 121),
                                            ),
                                          ),
                                          Positioned(
                                            left: 63.25,
                                            top: 15.0,
                                            right: null,
                                            bottom: null,
                                            width: 31.0,
                                            height: 23.0,
                                            child: GeneratedCheckoutNowWidget1(),
                                          )
                                        ]),
                                  ),
                                ),
                              )
                            ]),
                      ),
                    ),
                    Positioned(
                      left: 334.0,
                      top: 59.0,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 20.0,
                      child: GeneratedFrame4Widget(),
                    )
                  ]),
            ),
          ));
}

}
