import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro142widget/generated/GeneratedWidget47.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro142widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedmacbookpro142widget/generated/Generated12Widget1.dart';

/* Frame MacBook Pro 14" - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro142Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2106.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -993.0,
                              top: 1206.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 900.0,
                              child: Generated12Widget1(),
                            ),
                            Positioned(
                              left: 85.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 323.0,
                              height: 166.0,
                              child: GeneratedRectangle1Widget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 128.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 122.0,
                              child: GeneratedWidget47(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
