import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedBaseFormInputWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/Generated1231Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/Generated1Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedCommentWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedRectangle124Widget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedBaseDetailMenuLightFalseWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedVectorWidget28.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedQnAWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedBaseWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedBaseCommentWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_onewidget/generated/GeneratedRectangle136Widget.dart';

/* Frame qna_one
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQna_oneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 252, 252, 255),
                ),
              ),
              Positioned(
                left: 330.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedSearchWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.000030517578125,
                right: null,
                bottom: null,
                width: 376.0,
                height: 74.00003051757812,
                child: GeneratedRectangle124Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 70.00003051757812,
                child: GeneratedRectangle136Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 753.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 50.0,
                child: GeneratedBaseFormInputWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 52.00006866455078,
                child: GeneratedBaseDetailMenuLightFalseWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 105.0,
                child: GeneratedBaseCommentWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 85.0,
                child: GeneratedCommentWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget3(),
              ),
              Positioned(
                left: 15.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 19.79069709777832,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 31.0,
                child: GeneratedQnAWidget(),
              ),
              Positioned(
                left: 337.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget28(),
              ),
              Positioned(
                left: 72.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 65.0,
                child: Generated1231Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 160.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 24.0,
                child: GeneratedGroup30Widget(),
              )
            ]),
      ),
    ));
  }
}
