import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedVectorWidget31.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedCommentWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedRectangle124Widget4.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedGroup30Widget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedBaseWidget4.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedSmallBadgeWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedSmallBadgeWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedSearchWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedGroup30Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedRectangle136Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedQnAWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqna_twowidget/generated/GeneratedGroup21Widget.dart';

/* Frame qna_two
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQna_twoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 252, 252, 255),
                ),
              ),
              Positioned(
                left: 330.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 21.0,
                child: GeneratedSearchWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.000030517578125,
                right: null,
                bottom: null,
                width: 376.0,
                height: 74.00003051757812,
                child: GeneratedRectangle124Widget4(),
              ),
              Positioned(
                left: 302.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 18.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 70.00003051757812,
                child: GeneratedRectangle136Widget1(),
              ),
              Positioned(
                left: 15.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 198.0,
                child: GeneratedCommentWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget4(),
              ),
              Positioned(
                left: 15.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 19.79069709777832,
                child: GeneratedGroup13Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 31.0,
                child: GeneratedQnAWidget1(),
              ),
              Positioned(
                left: 337.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedVectorWidget31(),
              ),
              Positioned(
                left: 96.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 24.0,
                child: GeneratedGroup30Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 348.34210205078125,
                height: 186.0,
                child: GeneratedImage6Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 267.999755859375,
                height: 15.0,
                child: GeneratedGroup31Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 14.0,
                child: GeneratedSmallBadgeWidget1(),
              ),
              Positioned(
                left: 316.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 14.0,
                child: GeneratedSmallBadgeWidget2(),
              ),
              Positioned(
                left: -2.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 81.0,
                child: GeneratedGroup30Widget2(),
              )
            ]),
      ),
    ));
  }
}
