import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedRectangle124Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseBadgeWidget5.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseBadgeWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseMenuNavigationWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseBadgeWidget4.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseBadgeWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseBadgeWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseFormInputWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseBadgeWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedsearchwidget/generated/GeneratedBaseWidget1.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 99, 95, 255),
                ),
              ),
              Positioned(
                left: 376.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 375.99993896484375,
                height: 711.0000610351562,
                child: GeneratedRectangle124Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 20.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 4.547473508864641e-13,
                top: 53.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedBaseMenuNavigationWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 50.0,
                child: GeneratedBaseFormInputWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 30.0,
                child: GeneratedBaseBadgeWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 30.0,
                child: GeneratedBaseBadgeWidget1(),
              ),
              Positioned(
                left: 195.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 30.0,
                child: GeneratedBaseBadgeWidget2(),
              ),
              Positioned(
                left: 119.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 30.0,
                child: GeneratedBaseBadgeWidget3(),
              ),
              Positioned(
                left: 203.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 30.0,
                child: GeneratedBaseBadgeWidget4(),
              ),
              Positioned(
                left: 279.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 30.0,
                child: GeneratedBaseBadgeWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget1(),
              )
            ]),
      ),
    ));
  }
}
