import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget37.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget34.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget38.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedVectorWidget63.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget36.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseMenuNavigationWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedCardCardSeparatorWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget35.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseUnitListWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget31.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget33.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseSectionTitleWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget30.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget32.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedRectangle147Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseUnitListWidget4.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseUnitListWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedRectangle124Widget8.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseUnitListWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedWidget29.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedRectangle144Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseSectionTitleWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseUnitListWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/Generated11Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedBaseWidget8.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedSearchWidget8.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedRectangle146Widget4.dart';
import 'package:flutterapp/easyandquickapp/generatedbookmarkwidget/generated/GeneratedGroup13Widget10.dart';

/* Frame bookmark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookmarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 252, 252, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 97.00003051757812,
                child: GeneratedRectangle124Widget8(),
              ),
              Positioned(
                left: 9.094947017729282e-13,
                top: 53.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedBaseMenuNavigationWidget3(),
              ),
              Positioned(
                left: 1.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 65.0,
                child: GeneratedBaseSectionTitleWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 65.0,
                child: GeneratedBaseSectionTitleWidget1(),
              ),
              Positioned(
                left: -2.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 0.0,
                child: GeneratedCardCardSeparatorWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 58.0,
                child: GeneratedBaseUnitListWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 58.0,
                child: GeneratedBaseUnitListWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 58.0,
                child: GeneratedBaseUnitListWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 58.0,
                child: GeneratedBaseUnitListWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 58.0,
                child: GeneratedBaseUnitListWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget8(),
              ),
              Positioned(
                left: 25.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget63(),
              ),
              Positioned(
                left: 62.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 32.0,
                child: GeneratedRectangle144Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 26.0,
                child: GeneratedWidget29(),
              ),
              Positioned(
                left: 168.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 28.0,
                child: Generated11Widget(),
              ),
              Positioned(
                left: -2.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 81.0,
                child: GeneratedGroup13Widget10(),
              ),
              Positioned(
                left: 302.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 332.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 20.0,
                child: GeneratedWidget30(),
              ),
              Positioned(
                left: 120.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 24.0,
                child: GeneratedRectangle146Widget4(),
              ),
              Positioned(
                left: 302.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 21.0,
                child: GeneratedSearchWidget8(),
              ),
              Positioned(
                left: 234.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 22.0,
                child: GeneratedWidget31(),
              ),
              Positioned(
                left: 187.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 19.0,
                child: GeneratedWidget32(),
              ),
              Positioned(
                left: 234.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 22.0,
                child: GeneratedWidget33(),
              ),
              Positioned(
                left: 232.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 22.0,
                child: GeneratedWidget34(),
              ),
              Positioned(
                left: 232.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 22.0,
                child: GeneratedWidget35(),
              ),
              Positioned(
                left: 234.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 22.0,
                child: GeneratedWidget36(),
              ),
              Positioned(
                left: 232.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 19.0,
                child: GeneratedWidget37(),
              ),
              Positioned(
                left: 17.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 19.0,
                child: GeneratedRectangle147Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 18.0,
                child: GeneratedWidget38(),
              )
            ]),
      ),
    ));
  }
}
