import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedtestwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedtestwidget/generated/GeneratedSearchWidget9.dart';
import 'package:flutterapp/easyandquickapp/generatedtestwidget/generated/GeneratedFrame2Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedtestwidget/generated/GeneratedChickSolutionWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedtestwidget/generated/GeneratedWidget41.dart';

/* Frame test
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 900.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 900.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1142.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 900.0,
                              child: GeneratedFrame2Widget1(),
                            ),
                            Positioned(
                              left: 267.0,
                              top: 350.0,
                              right: null,
                              bottom: null,
                              width: 800.0,
                              height: 80.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 841.0,
                              height: 125.0,
                              child: GeneratedSearchWidget9(),
                            ),
                            Positioned(
                              left: 1003.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 64.05693817138672,
                              height: 50.0,
                              child: GeneratedWidget41(),
                            ),
                            Positioned(
                              left: 342.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 651.0,
                              height: 122.0,
                              child: GeneratedChickSolutionWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
