import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedBaseMenuNavigationWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedRectangle124Widget2.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedChevronrightWidget4.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedFrame35Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedIwantApluscnuackrWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedVectorWidget24.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedBaseWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedWidget8.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedGroup7Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedWidget9.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedChevronrightWidget2.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedChevronrightWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedUserWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedChevronrightWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedccountwidget/generated/GeneratedFrame34Widget2.dart';

/* Frame ccount
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCcountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 99, 95, 255),
                ),
              ),
              Positioned(
                left: 375.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 375.9999694824219,
                height: 467.0000305175781,
                child: GeneratedRectangle124Widget2(),
              ),
              Positioned(
                left: 9.094947017729282e-13,
                top: 53.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedBaseMenuNavigationWidget1(),
              ),
              Positioned(
                left: 138.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 41.0,
                child: GeneratedUserWidget1(),
              ),
              Positioned(
                left: 86.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 31.0,
                child: GeneratedIwantApluscnuackrWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 15.0,
                child: GeneratedWidget5(),
              ),
              Positioned(
                left: 25.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 20.0,
                child: GeneratedFrame34Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 18.0,
                child: GeneratedFrame35Widget(),
              ),
              Positioned(
                left: 288.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedChevronrightWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 23.0,
                child: GeneratedWidget8(),
              ),
              Positioned(
                left: 290.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedChevronrightWidget2(),
              ),
              Positioned(
                left: 480.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedChevronrightWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 24.0,
                child: GeneratedWidget9(),
              ),
              Positioned(
                left: 290.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedChevronrightWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget2(),
              ),
              Positioned(
                left: 130.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 110.0,
                child: GeneratedGroup7Widget1(),
              ),
              Positioned(
                left: 236.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget24(),
              ),
              Positioned(
                left: 1.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 81.0,
                child: GeneratedGroup12Widget(),
              )
            ]),
      ),
    ));
  }
}
