import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedgroup8widget/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/easyandquickapp/generatedgroup8widget/generated/GeneratedBaseNavigationWidget13.dart';

/* Group Group 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 70.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 70.0,
              child: GeneratedBaseNavigationWidget13(),
            ),
            Positioned(
              left: 226.0,
              top: 22.0,
              right: null,
              bottom: null,
              width: 23.0,
              height: 23.0,
              child: GeneratedImage2Widget1(),
            )
          ]),
    ));
  }
}
