import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedsamplewidget/generated/GeneratedLeftWidget.dart';
import 'package:flutterapp/easyandquickapp/generatedsamplewidget/generated/GeneratedFigmaTutorialWidget1.dart';
import 'package:flutterapp/easyandquickapp/generatedsamplewidget/generated/GeneratedGoodmorsingWidget1.dart';

/* Frame sample
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSampleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 900.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 900.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 900.0,
                              child: GeneratedLeftWidget(),
                            ),
                            Positioned(
                              left: 908.0,
                              top: 260.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 242.0,
                              child: GeneratedGoodmorsingWidget1(),
                            ),
                            Positioned(
                              left: 911.0,
                              top: 520.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 122.0,
                              child: GeneratedFigmaTutorialWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
