import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedgroup27widget/generated/GeneratedWidget39.dart';
import 'package:flutterapp/easyandquickapp/generatedgroup27widget/generated/GeneratedPlusMathWidget.dart';

/* Group Group 27
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup27Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 96.0,
      height: 26.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 17.26618766784668,
              top: 2.0,
              right: null,
              bottom: null,
              width: 80.73381042480469,
              height: 26.0,
              child: GeneratedWidget39(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 13.812949180603027,
              height: 20.0,
              child: GeneratedPlusMathWidget(),
            )
          ]),
    ));
  }
}
