import 'package:flutter/material.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedWidget23.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup21Widget2.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedWidget24.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup30Widget4.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedWidget25.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup13Widget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedWidget26.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedWidget21.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedRectangle124Widget6.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedWidget22.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedQnAWidget3.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/easyandquickapp/generatedqnawidget/generated/GeneratedBaseWidget6.dart';

/* Frame qna
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQnaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 252, 252, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.000030517578125,
                right: null,
                bottom: null,
                width: 376.0,
                height: 74.00003051757812,
                child: GeneratedRectangle124Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBaseWidget6(),
              ),
              Positioned(
                left: 17.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 31.0,
                child: GeneratedQnAWidget3(),
              ),
              Positioned(
                left: 302.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 18.0,
                child: GeneratedGroup21Widget2(),
              ),
              Positioned(
                left: -5.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 81.0,
                child: GeneratedGroup13Widget3(),
              ),
              Positioned(
                left: 103.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 24.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 244.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 21.0,
                child: GeneratedWidget21(),
              ),
              Positioned(
                left: 243.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 24.0,
                child: GeneratedWidget22(),
              ),
              Positioned(
                left: 239.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 21.0,
                child: GeneratedWidget23(),
              ),
              Positioned(
                left: 239.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 24.0,
                child: GeneratedWidget24(),
              ),
              Positioned(
                left: 239.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 24.0,
                child: GeneratedWidget25(),
              ),
              Positioned(
                left: 239.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 24.0,
                child: GeneratedWidget26(),
              ),
              Positioned(
                left: 17.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: GeneratedGroup30Widget4(),
              ),
              Positioned(
                left: 19.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 52.0,
                child: GeneratedGroup24Widget(),
              )
            ]),
      ),
    ));
  }
}
